"""add_missing_indexes

Revision ID: 6cdb894dcd81
Revises: 039f3065c89e
Create Date: 2026-06-02 12:23:03.424570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cdb894dcd81'
down_revision: Union[str, Sequence[str], None] = '039f3065c89e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_job_applications_company_name', 'job_applications', ['company_name'], unique=False)
    op.create_index('ix_job_applications_status', 'job_applications', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_applications_status', table_name='job_applications')
    op.drop_index('ix_job_applications_company_name', table_name='job_applications')
    # ### end Alembic commands ###
